version: '3'

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: copelco
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db11:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_USER: copelco
    volumes:
      - pgdata11:/var/lib/postgresql/data
    ports:
      - "54311:5432"

  elasticsearch24:
    image: elasticsearch:2.4-alpine
    ports:
      - "9200:9200"

  memcached:
    image: memcached:1.6-alpine
    restart: always
    ports:
      - "11211:11211"

volumes:
  pgdata:
  pgdata11:
